---
builds:
  - binary: lunaform
    main: ./server/cmd/lunaform-server/main.go
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
  - binary: lunaform-client
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
    main: ./cli/main.go
    ldflags:
      - -X github.com/drewsonne/lunaform/cli/cmd.version={{.Version}}
git:
  short_hash: true

brew:
  name: lunaform
  github:
    owner: drewsonne
    name: homebrew-tap
  install: |
    bin.install "lunaform"
    bin.install "lunaform-client"

nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

  replacements:
    amd64: 64-bit
    darwin: macOS

  vendor: Drew J. Sonne
  homepage: https://github.com/drewsonne/lunaform
  maintainer: Drew J. Sonne <drew.sonne@gmail.com>
  license: Apache 2.0
  formats:
    - deb
    - rpm