language: go

addons:
  apt:
    packages:
    # needed for the nfpm pipe:
    - rpm
    sources:
    - sourceline: deb https://dl.bintray.com/go-swagger/goswagger-debian ubuntu main

# needed for the docker pipe
services:
- docker

install:
  - sudo apt-get install swagger

after_success:
# docker login is required if you want to push docker images.
# DOCKER_PASSWORD should be a secret in your .travis.yml configuration.
- test -n "$TRAVIS_TAG" && docker login -u=myuser -p="$DOCKER_PASSWORD"

# calls goreleaser
deploy:
- provider: script
  skip_cleanup: true
  script: curl -sL https://git.io/goreleaser | bash
  on:
    tags: true
    condition: $TRAVIS_OS_NAME = linux && $TRAVIS_GO_VERSION =~ ^1\.10(\.[0-9]+)?$
